### ISSUE TITLE
RuntimeError upon import: missing getitem/setitem

### ISSUE THREAD

**Issue by peytondmurray** [peytondmurray/quaddtype#1]
Upon installing the `quaddtype` package with `pip install .`, importing `quaddtype` fails:

```
>>> import quaddtype
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pdmurray/.pyenv/versions/mambaforge/envs/numpy-dev/lib/python3.9/site-packages/quaddtype/__init__.py", line 1, in <module>
    from ._quaddtype_main import QuadDType
RuntimeError: A DType must provide a getitem/setitem (there may be an exception here in the future if no scalar type is provided)
```

However, I'm already providing `getitem`/`setitem` [here](https://github.com/peytondmurray/quaddtype/blob/2951d1ce47b71d8602e4c3750e8632c5fa5f88d1/quaddtype/src/dtype.c#L76), in the `QuadDType_Slots`, which is passed to the `DTypeSpec` [further down](https://github.com/peytondmurray/quaddtype/blob/2951d1ce47b71d8602e4c3750e8632c5fa5f88d1/quaddtype/src/dtype.c#L125). @seberg I hope it's okay if I mention you here - I based most of this off your [SciPy 2022 talk repository](https://github.com/seberg/talk_unitdtype); do you have any clue what I'm missing with this implementation?

**Comment by seberg** [comment]
This cool, thanks for the ping @peytondmurray!  This does unfortunately look like the silly/annoying little bug that I did not notice in the NumPy 1.23.x line.  I am not 100% sure whether it has been backported (but can check).

So, if you are not using a development version, could you install it from the anaconda sources maybe (I guess it is linux only): https://anaconda.org/scipy-wheels-nightly/numpy

If that is not a trivial fix, please just ping me, and I will try it out locally and see what is going on.  I don't want you to spend time chasing the little things when I probably can find the solution much quicker (and likely they are my bugs anyway).

**Comment by peytondmurray** [comment]
@seberg Sorry to revive this so long after your response - I got really busy with some other projects but I'm back picking this up now. You were definitely right about needing to install the latest nightly build, I've installed the latest version (`1.24.0.dev0+973.g7776bc616`) but now am getting a different issue:

```
RuntimeError: DType API version 5 did not match header version 4. Please update the import statement and check for API changes.
```

Looking at the `experimental_dtype_api.h`, there's a check performed [just below here](https://github.com/numpy/numpy/blob/8d61ebc25a117337d148f1e3d96066653bd6419a/numpy/core/include/numpy/experimental_dtype_api.h#L461) which is where the import fails. I know that the included file is the correct one, because `meson-python` generates a compilation database for language servers and other developer tooling which has the right include directory. Is there any way that `__EXPERIMENTAL_DTYPE_VERSION` define is set somewhere else which conflicts?

**Comment by seberg** [comment]
Hmmm, on pip I would suggest passing `--no-build-isolation` to ensure the compilation runs in the environment with the new NumPy?

`__EXPERIMENTAL_DTYPE_VERSION` is defined right above that check to 5.  The version currently does exist a second time (I should remove that) [here](https://github.com/numpy/numpy/blob/8d61ebc25a117337d148f1e3d96066653bd6419a/numpy/core/src/multiarray/experimental_public_dtype_api.c#L19), but they are both 5.

Those are the two versions which are mismatching, maybe the error message was wrong, but either the runtime NumPy or the compile time NumPy is older.  Probably the compile time NumPy (header).

I had problems on debian that it would always find the system version because debian copies the headers next to the Python headers (where they should not need to be) and then always finds the system NumPy headers.  But that itself can't really be the issue here.

**Comment by peytondmurray** [comment]
:facepalm: That was is - `pyproject.toml` specifies numpy as a build time dependency. Thanks!
